[2023-03-20 18:04:38,466: INFO: stage_01_prepare_data]: 
********************
[2023-03-20 18:04:38,466: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2023-03-20 18:04:38,473: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-03-20 18:04:38,475: INFO: common]: yaml file: params.yaml loaded successfully
[2023-03-20 18:04:38,476: INFO: common]: created directory at: artifacts\prepared
[2023-03-20 18:04:40,233: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data completed!<<<<<

[2023-03-21 17:14:19,198: INFO: stage_01_prepare_data]: 
********************
[2023-03-21 17:14:19,199: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data started <<<<<
[2023-03-21 17:14:19,203: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-03-21 17:14:19,205: INFO: common]: yaml file: params.yaml loaded successfully
[2023-03-21 17:14:19,205: INFO: common]: created directory at: artifacts\prepared
[2023-03-21 17:14:21,386: INFO: stage_01_prepare_data]: >>>>> stage Prepare_data completed!<<<<<

[2023-03-21 17:20:51,653: INFO: stage_02_featurization]: 
********************
[2023-03-21 17:20:51,653: INFO: stage_02_featurization]: >>>>> stage Featurization started <<<<<
[2023-03-21 17:20:51,655: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-03-21 17:20:51,657: INFO: common]: yaml file: params.yaml loaded successfully
[2023-03-21 17:20:51,657: INFO: common]: created directory at: artifacts\features
[2023-03-21 17:20:51,944: INFO: common]: The input dataframeartifacts\prepared\train.tsvsize id (17536, 3) is read.
[2023-03-21 17:21:02,719: ERROR: stage_02_featurization]: 'DataFrame' object has no attribute 'id'
Traceback (most recent call last):
  File "src/stage_02_featurization.py", line 81, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_featurization.py", line 59, in main
    save_matrix(df=df_train, matrix= train_words_tfidf_matrix, out_path= featurize_train_data_path)
  File "c:\users\deepak.thakur\work\dvc-nlp-project-with-docs\src\utils\data_mgmt.py", line 34, in save_matrix
    id_matrix = df.id
  File "c:\Users\deepak.thakur\Work\DVC-NLP-Project-with-docs\env\lib\site-packages\pandas\core\generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'id'
[2023-03-21 17:21:15,988: INFO: stage_02_featurization]: 
********************
[2023-03-21 17:21:15,988: INFO: stage_02_featurization]: >>>>> stage Featurization started <<<<<
[2023-03-21 17:21:15,992: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-03-21 17:21:15,995: INFO: common]: yaml file: params.yaml loaded successfully
[2023-03-21 17:21:15,996: INFO: common]: created directory at: artifacts\features
[2023-03-21 17:21:16,172: INFO: common]: The input dataframeartifacts\prepared\train.tsvsize id (17536, 3) is read.
[2023-03-21 17:21:26,720: INFO: common]: The input dataframeartifacts\prepared\test.tsvsize id (7464, 3) is read.
[2023-03-21 17:21:30,788: INFO: stage_02_featurization]: >>>>> stage Featurization completed!<<<<<

